### ISSUE TITLE
Question: Adding lab linting

### ISSUE THREAD

**Issue by rankida** [continuationlabs/eslint-plugin-hapi#7]
We use [lab](https://github.com/hapijs/lab) to test in our hapi project.

Because lab is a hapi repo I was wondering if you would be interested in accepting a PR for adding lab linting rules? These would be heavily inspired by [eslint-plugin-jasmine](https://github.com/tlvince/eslint-plugin-jasmine).

The rule I am particularly interested in is to stop me pushing code with `describe.only` or `it.only`.
For example, the equivalent in jasmine's plugin would be
![image](https://cloud.githubusercontent.com/assets/295619/23911019/62661f80-08d3-11e7-9209-00ce0a42135f.png)
And I was thinking something like this for lab
![image](https://cloud.githubusercontent.com/assets/295619/23911041/7673946c-08d3-11e7-8e9d-7c68ce28e9aa.png)

If you are not interested I am happy to create a separate package to collect some lab linting rules.

Thanks

**Comment by cjihrig** [comment]
Thanks for the proposal. This plugin is for enforcing the hapi style guide though, so I don't think we should mix in something like this. I definitely see the usefulness for your rules though, so I'd encourage you to publish them separately. Thanks again!

**Comment by Marsup** [comment]
Shouldn't it be in the hapi style guide though ? Pushing this is usually an error.

**Comment by cjihrig** [comment]
I don't personally use them, but I think there are probably valid uses for them. Wanna open an issue in contrib and see what others think?

**Comment by rankida** [comment]
If anyone is interested you can find my attempts at lab linting in [`eslint-plugin-lab`](https://www.npmjs.com/package/eslint-plugin-lab) on npm
